# -*- coding: utf-8 -*-
"""viz_correlation_cac40

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjc2oeOybsGvcWj9SZYu3Vgp8pDrqmKy
"""

import yfinance as yf
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

CAC40_TICKERS = [
    'AC.PA', 'AI.PA', 'AIR.PA', 'BNP.PA', 'CAP.PA', 'CS.PA',
    'DSY.PA', 'ENGI.PA', 'GLE.PA', 'KER.PA', 'MC.PA', 'OR.PA',
    'RNO.PA', 'SAN.PA', 'SU.PA', 'TTE.PA', 'VIE.PA', 'VIV.PA'
]

print("Téléchargement des données pour la visualisation...")

data = yf.download(CAC40_TICKERS, period="1y", auto_adjust=True)['Close']

returns = data.pct_change().dropna()


correlation_matrix = returns.corr()


plt.figure(figsize=(12, 10))
sns.set_theme(style="white")


heatmap = sns.heatmap(correlation_matrix,
            annot=True,
            fmt=".1f",
            cmap='coolwarm',
            vmin=-1, vmax=1,
            linewidths=.5,
            square=True)

plt.title('Matrice de Corrélation du CAC 40\n(Pré-analyse pour SVD)', fontsize=16)
plt.xlabel('Actions', fontsize=12)
plt.ylabel('Actions', fontsize=12)


plt.tight_layout()


print("Graphique généré avec succès.")
plt.show()